### ISSUE TITLE
Issues of big food

### ISSUE THREAD

**Issue by UIT-20520369** [UIT-20520369/Snake-Game-Project#10]
1) là khi mồi lớn xuất hiện đôi lúc nó lại biến thành mồi nhỏ "o"

**Comment by UIT-20520724** [comment]
### Sửa lại phần else trong hàm anmoi:
_if(MoiAn % 5 !=4)
            {
                gotoxy(FOOD.x, FOOD.y);
                SetColor(13);
                cout << "o";
                return 0;
            }
            else
            {
                gotoxy(FOOD.x, FOOD.y);
                SetColor(13);
                cout << "0";
                return 0;_
